### ISSUE TITLE
Feature Request: Color bundle icon (email) 

### ISSUE THREAD

**Issue by vtexperts** [teresa-ou/inboxy#12]
Given that Gmail has colors for labels, it might be nice to color the email icon with the same color as the label (if assigned one).
![chrome_2020-03-31_13-40-34 1](https://user-images.githubusercontent.com/17834854/78063067-382b5600-7355-11ea-9758-60292d6fa960.png)

**Comment by atippett** [comment]
To further discussion.. it seems like we're already applying the label color on individual emails, should not the same treatment be applied to the bundles?

![Screen Shot 2020-08-06 at 8 41 24 AM](https://user-images.githubusercontent.com/189563/89552418-f4dc6a80-d7c0-11ea-95b7-c321b01a0c3c.png)

![Screen Shot 2020-08-06 at 8 41 32 AM](https://user-images.githubusercontent.com/189563/89552440-fe65d280-d7c0-11ea-83d8-84765e7dd4b7.png)

**Comment by tmenier** [comment]
+1. This would be a fantastic enhancement.

And THANK YOU for creating this! It's improved my email life significantly and even made me just a little less bitter/spiteful about the demise of Inbox. :)

**Comment by jzelinskie** [comment]
Continuing the discussion from #64 

>As for the colored boxes around the bundle names, these boxes look similar to labels, which makes it seem like a secondary component rather than the main text for those rows.

I think we should fully embrace the idea that the bundles are driven by labels by adopting the label's styles in the row.
Here's some strawmen from me:

<img width="216" alt="Screen Shot 2020-12-30 at 1 45 22 AM" src="https://user-images.githubusercontent.com/343539/103334907-3526d880-4a41-11eb-969f-c9e004e315c6.png">
<img width="211" alt="Screen Shot 2020-12-30 at 1 45 40 AM" src="https://user-images.githubusercontent.com/343539/103334911-38ba5f80-4a41-11eb-877d-4408cfcff987.png">

```css
.bundle-and-count {
  background-color: rgb(73, 134, 231);
  color: rgb(255, 255, 255);
  border-radius: 4px;
  padding: 0 4px;
}

.bundle-count {
  font-size: .75rem;
  margin-left: 4px;
  letter-spacing: .3px;
  opacity: 0.75;
}
```

I only took CSS from other places:
- labels → colors, border, and padding
- responses → margin, font size/spacing, then I added opacity to substitute the font color not being relative
